### ISSUE TITLE
AttributeError: 'module' object has no attribute 'th_Double_fft2'

### ISSUE THREAD

**Issue by kingkongkai** [bamos/block#10]
I get the following error:

  File "/packages/development/anaconda/2-4.3.1/lib/python2.7/site-packages/pytorch_fft/fft/fft.py", line 41, in fft2
    f = th_fft.th_Double_fft2
AttributeError: 'module' object has no attribute 'th_Double_fft2'

Any idea how to fix this?

**Comment by bamos** [comment]
This doesn't look like part of block. Should this have been sent to locuslab/pytorch_fft?

**Comment by kingkongkai** [comment]
Yes, sorry, I followed a link on their repo which lead here and I didn't notice. Re-posting.
