### ISSUE TITLE
pip install throws error code 1

### ISSUE THREAD

**Issue by kyillene** [bamos/block#13]
Hello,
I am using pytorch with cuda. When i am trying to install pytorch_fft it throws the following error. 
I am running pycharm terminal as an administrator and I already tried following upgrade trick that is suggested as a fix.

`pip install --upgrade setuptools`

Is this problem related to pytorch/pytorch_fft or it is a generic python problem that I need to seek solution somewhere else.

`Collecting pytorch-fft
  Downloading https://files.pythonhosted.org/packages/f6/d8/00edd29004d9943ebd42c665ac6f25ac57c7b9165656da514bb62737d85d/pytorch_fft-0.14.tar.gz

    Complete output from command python setup.py egg_info:

    error in pytorch_fft setup command: 'C:\\Users\\MONSTER\\AppData\\Local\\Temp\\pip-build-oyy5iyjr\\pytorch-fft\\build.py:ffi' must be of the form 'path/build.py:ffi_variable'

    Including CUDA code.
    ----------------------------------------
`
Command  'python setup.py egg_info' failed with error code 1 in C:\Users\MONSTER\AppData\Local\Temp\pip-build-oyy5iyjr\pytorch-fft\
`

Thanks already!

**Comment by SongFGH** [comment]
I am also have this question!!!
How to sole this???

**Comment by kyillene** [comment]
Unfortunately I couldn't solve the problem instead I found a workaround related to my problem. So I am sorry but I cannot help with that.

**Comment by SongFGH** [comment]
Thanks for responding! I have found a torch.fft function in Pytorch 1.0. So , I don't need to install this package.
